language: c

install: 
    - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version

script: hugo --minify -v

after_success:
    - cd public
    - git init
    - git config user.name "mycad"
    - git config user.email "3594545056@qq.com"
    - git add .
    - git commit -m "Update docs"
    - git push -f https://$GITHUB_TOKEN@github.com/mycad/mycad.github.io.git master