metaDataFormat: yaml
hasCJKLanguage: true
title: MyCAD
paginate: 10
summaryLength: 200
permalinks:
    post: /:year/:month/:day/:filename
    
menu:
  main:
  - name: 机型
    url: /acmodel/
    pre: plane
    weight: 1
  - name: 发动机
    url: /eng/
    pre: gears
    weight: 2
  - name: 件号
    url: /pn/
    pre: cubes
    weight: 3
  - name: 颁发单位
    url: /admin/
    pre: gavel
    weight: 4
  - name: 制造商
    url: /mfr/
    pre: wrench
    weight: 5
  - name: 总清单
    url: /archive/
    pre: archive
    weight: 6
  - name: 关于
    url: /about/
    pre: heart
    weight: 7

taxonomies:
  category: categories
  tag: tags
  acmodel: acmodels
  eng: engs
  admin: admins
  mfr: mfrs
  pn: pns
  
params:
    site_description: 本站所有CAD来自CAAC
    footer_description: 欢迎指出本站的内容错误！
    baidu_tongji_id: 4cc3fd6dcaf01a5a6244f36c72ccace8
    busuanzi_tongji_site: busuanzi.ibruce.info
    email: 56649783@qq.com
    github_username: mycad
    #weibo_username: 
    #zhihu_username: 
    #linkedIn_username: 
    #dribbble_username:
    #twitter_username: 
    #facebook_username: 
